### ISSUE TITLE
too large a matrix for LINPACK

### ISSUE THREAD

**Issue by JohannesWiesner** [ejolly/pymer4#129]
Hi,

I have a large dataframe with ~16.000.000 rows. On top of that I have two categorical predictors with lots of factor levels. I am currently facing this error:

![Screenshot_20231024_174515](https://github.com/ejolly/pymer4/assets/48254290/55de3050-9c25-402d-b8ac-5ee602181e07)

Seems like this is documented:

https://github.com/lme4/lme4/issues/387
https://stackoverflow.com/questions/56586369/r-mlogit-package-use-lapack-instead-of-linpack

Do you have any idea how to solve this? RAM shouldn't be a problem (currently running this on a 128 GB RAM VM and could easily also switch to our server with even more RAM) but seems to be a software restriction?

And I also don't know if you could tweak this using pymer4?

**Comment by ejolly** [comment]
@JohannesWiesner Hmm this seems to be a limitation of `qr` decomposition in R. If there's a way to ask `lme4` to use a different solver using [`lmerControl`](https://rdrr.io/cran/lme4/man/lmerControl.html) options, `pymer4` supports passing those options in, e.g. like [this](https://github.com/ejolly/pymer4/blob/master/pymer4/tests/test_models.py#L108C20-L108C20). 

Otherwise I'm going to mark this is out-of-scope for `pymer4` because there's not much we can do beyond what `lme4` and `R` are already doing.
