### ISSUE TITLE
Why is conda installing R slower per the README? 

### ISSUE THREAD

**Issue by andportnoy** [ejolly/pymer4#32]
Would be grateful if you could clarify why it's slower than installing the relevant R packages manually.

**Comment by ejolly** [comment]
I haven't really explored the reason. My hunch is because conda-forge contains precompiled binary files for R and the relevant packages and they aren't optimized/built for a specific system, therefore making them easier to install. Whereas when you download from CRAN you might be getting the best /most compatible version for your system by building it locally. Could be wrong about this tho!

**Comment by andportnoy** [comment]
@ejolly That's right, `install.packages` compiles the packages while `conda` doesn't, that makes sense, thank you!
