### ISSUE TITLE
Lmer .fixef and .coefs - opposite to R behavior

### ISSUE THREAD

**Issue by ecoronado92** [ejolly/pymer4#65]
I was testing this awesome package and noticed there was a bit of a discrepancy on what I get when I call `.fixef` and `.coefs` in the Python model and when I use `coef(summary(model))[ , "Estimate"]` and `coefs()` in R , respectively.

For example,  the `.fixef` method provides the estimates that include fixed + random effects in Python (when I would think it  only provides fixed effect estimates). Similarly, the `coefs` method provides the fixed effects which is the other way around in R.

`ranef` works the same as in R 😄 

It's just a minor thing, but it might cause some headaches to whoever is used to doing stuff in R. 👍 

I tested this with the `sleepstudy` lme4 data

**Comment by ejolly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug fixes](https://trello.com/c/t3UDNQMg/7-bug-fixes)

**Comment by ejolly** [comment]
Thanks for bringing this up @ecoronado92. This was an intentional design decision because I wasn't a fan of how R does it. In my mind the intuition is:  

- `coef` = "top level" estimates, i.e. summary output of the model that can be used to make predictions on new datasets  
- `fixef` = group/cluster level _fixed effects_, i.e. conceptually similar to coefficients estimated if one were to run a separate `lm` per cluster  
- `ranef` = group/cluster _random effects_, i.e. deviance of each cluster with respect to `coef`

I can add a note to the docs for anyone who expects idiomatic R like behavior.

**Comment by ecoronado92** [comment]
@ejolly totally understand, yeah just adding a note would be super helpful. 

I normally take `fixed` to be population effects (i.e. same for all groups) and `coefs` as being the combination of `fixef` + `ranef` (deviance), thus why it was confusing to me.

Regardless it's awesome you brought this to Python!

**Comment by ejolly** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation updates](https://trello.com/c/pvp8cGHL/10-documentation-updates)
